// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type List struct {
	ID          string  `json:"id"`
	User        *User   `json:"user"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Color       string  `json:"color"`
	Tasks       []*Task `json:"tasks"`
}

type NewList struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type NewTag struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type NewTask struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Deadline    string    `json:"deadline"`
	Status      string    `json:"status"`
	Color       string    `json:"color"`
	TagIDs      []*string `json:"tagIDs"`
	ListIDs     []*string `json:"listIDs"`
}

type NewUser struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Tag struct {
	ID          string `json:"id"`
	User        *User  `json:"user"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

type Task struct {
	ID          string  `json:"id"`
	User        *User   `json:"user"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Deadline    string  `json:"deadline"`
	Status      string  `json:"status"`
	Color       string  `json:"color"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	Tags        []*Tag  `json:"tags"`
	Lists       []*List `json:"lists"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
